### PR TITLE
refactor: update author and license

### PR DESCRIPTION
**Pull request by boogsbunny**
## Background

This PR updates the author, the homepage link, and the license to reflect the new maintainers of this package.

## Changes

- Update README
- Update homepage
- Update license

### CODE REVIEW

**Comment by aadcg** [comment]
@boogsbunny this PR should be a single commit so please squash.

**Comment by jmercouris** [comment]
We could use the `squash and merge` button :-)

**Comment by aadcg** [comment]
@jmercouris, I assigned you for a review before merging myself since it concerns legal aspects. Thanks!

**Comment by jmercouris** [comment]
Aha! I see! Well, it looked fine as well when I checked it out!

**Pull request merged**
